SpeechBalloonLayout:
  LineLengthNarrow: 6
  LineLengthWide: 12
  WidthInBlocksNarrow: 2.1
  WidthInBlocksWide: 2.6
  HasBalloon: true
  BalloonMaterial: WHITE_STAINED_GLASS
  LinePrefix: ""
  LinePitch: 0.26
  CustomModelDataNarrow:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  CustomModelDataWide:
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
  PositionLeft:
    x: -0.3
    y: 0
    z: 0
  PositionRight:
    x: 0.3
    y: 0
    z: 0
  PositionTop:
    x: 0.8
    y: 0.3
    z: 0
